// src/frontend/src/lib/components/ui/PageHeader.svelte
<script lang="ts">
	import { cn } from '$lib/utils';

	let { title, description, actions, className } = $props();
</script>

<div class={cn('mb-6 flex items-start justify-between gap-4', className)}>
	<div class="min-w-0">
		<h1 class="font-display text-2xl font-bold leading-tight text-foreground">
			{title}
		</h1>
		{#if description}
			<p class="mt-1 text-sm text-muted-foreground">{description}</p>
		{/if}
	</div>
	{#if actions}
		<div class="flex flex-wrap items-center gap-2 shrink-0">
			{@render actions()}
		</div>
	{/if}
</div>

// src/frontend_react_backup/src/components/ui/PageHeader.tsx
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { ReactNode } from "react";

interface PageHeaderProps {
  title: string;
  description?: string;
  actions?: ReactNode;
  className?: string;
}

export default function PageHeader({
  title,
  description,
  actions,
  className,
}: PageHeaderProps) {
  return (
    <div
      data-ocid="page.header"
      className={cn("flex items-start justify-between gap-4 mb-6", className)}
    >
      <div className="min-w-0">
        <h1 className="text-2xl font-display font-bold text-foreground leading-tight">
          {title}
        </h1>
        {description && (
          <p className="text-sm text-muted-foreground mt-1">{description}</p>
        )}
      </div>
      {actions && (
        <div className="flex items-center gap-2 shrink-0 flex-wrap">
          {actions}
        </div>
      )}
    </div>
  );
}

export { Button };
