// src/frontend/src/components/layout/Navbar.tsx
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { useAppStore } from "@/store/appStore";
import type { UserRole } from "@/types";
import { formatDistanceToNow } from "date-fns";
import {
  Bell,
  ChevronDown,
  LogOut,
  Menu,
  Moon,
  Search,
  Settings,
  Sun,
  User,
} from "lucide-react";

interface NavbarProps {
  title?: string;
}

const roles: { value: UserRole; label: string }[] = [
  { value: "super_admin", label: "Super Admin" },
  { value: "school_admin", label: "School Admin" },
  { value: "teacher", label: "Teacher" },
  { value: "parent", label: "Parent" },
  { value: "student", label: "Student" },
];

const notifColors = {
  info: "bg-blue-500",
  success: "bg-emerald-500",
  warning: "bg-amber-500",
  error: "bg-red-500",
};

export default function Navbar({ title }: NavbarProps) {
  const {
    isDarkMode,
    toggleDarkMode,
    toggleSidebar,
    searchQuery,
    setSearchQuery,
    notifications,
    markNotificationRead,
    markAllNotificationsRead,
    currentRole,
    setCurrentRole,
    unreadCount,
  } = useAppStore();

  const unread = unreadCount();
  const currentRoleLabel =
    roles.find((r) => r.value === currentRole)?.label ?? "Super Admin";

  return (
    <header
      data-ocid="navbar"
      className="h-14 bg-card border-b border-border flex items-center gap-3 px-4 shrink-0 shadow-xs"
    >
      {/* Left */}
      <div className="flex items-center gap-2 min-w-0">
        <Button
          variant="ghost"
          size="icon"
          onClick={toggleSidebar}
          data-ocid="navbar.sidebar_toggle"
          className="shrink-0"
          aria-label="Toggle sidebar"
        >
          <Menu className="w-4 h-4" />
        </Button>
        {title && (
          <h1 className="text-sm font-semibold text-foreground hidden md:block truncate">
            {title}
          </h1>
        )}
      </div>

      {/* Search */}
      <div className="flex-1 max-w-sm mx-auto">
        <div className="relative">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
          <Input
            placeholder="Search schools, students, leads…"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            data-ocid="navbar.search_input"
            className="pl-9 h-8 text-sm bg-muted/50 border-input/50 focus:bg-background"
          />
          <kbd className="absolute right-2 top-1/2 -translate-y-1/2 hidden sm:flex items-center gap-0.5 text-[10px] text-muted-foreground bg-muted px-1 rounded">
            ⌘K
          </kbd>
        </div>
      </div>

      {/* Right actions */}
      <div className="flex items-center gap-1 shrink-0">
        {/* Role switcher */}
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="outline"
              size="sm"
              data-ocid="navbar.role_switcher"
              className="h-8 text-xs gap-1 hidden md:flex border-input/50"
            >
              {currentRoleLabel}
              <ChevronDown className="w-3 h-3" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-44">
            <DropdownMenuLabel className="text-xs">
              Switch Role
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            {roles.map((role) => (
              <DropdownMenuItem
                key={role.value}
                onClick={() => setCurrentRole(role.value)}
                data-ocid={`navbar.role.${role.value}`}
                className={cn(
                  "text-xs cursor-pointer",
                  currentRole === role.value &&
                    "bg-accent text-accent-foreground",
                )}
              >
                {role.label}
              </DropdownMenuItem>
            ))}
          </DropdownMenuContent>
        </DropdownMenu>

        {/* Dark mode */}
        <Button
          variant="ghost"
          size="icon"
          onClick={toggleDarkMode}
          data-ocid="navbar.theme_toggle"
          className="w-8 h-8"
          aria-label="Toggle dark mode"
        >
          {isDarkMode ? (
            <Sun className="w-4 h-4" />
          ) : (
            <Moon className="w-4 h-4" />
          )}
        </Button>

        {/* Notifications */}
        <Popover>
          <PopoverTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              data-ocid="navbar.notifications_button"
              className="w-8 h-8 relative"
              aria-label="Notifications"
            >
              <Bell className="w-4 h-4" />
              {unread > 0 && (
                <span className="absolute -top-0.5 -right-0.5 w-4 h-4 bg-destructive text-destructive-foreground text-[10px] font-bold rounded-full flex items-center justify-center">
                  {unread}
                </span>
              )}
            </Button>
          </PopoverTrigger>
          <PopoverContent
            align="end"
            className="w-80 p-0"
            data-ocid="navbar.notifications.popover"
          >
            <div className="flex items-center justify-between px-4 py-3 border-b border-border">
              <span className="text-sm font-semibold">Notifications</span>
              <button
                type="button"
                onClick={markAllNotificationsRead}
                data-ocid="navbar.notifications.mark_all_read"
                className="text-xs text-accent hover:underline"
              >
                Mark all read
              </button>
            </div>
            <ScrollArea className="h-80">
              {notifications.slice(0, 8).map((notif) => (
                <button
                  key={notif.id}
                  type="button"
                  onClick={() => markNotificationRead(notif.id)}
                  data-ocid={`navbar.notification.${notif.id}`}
                  className={cn(
                    "w-full text-left px-4 py-3 border-b border-border/50 hover:bg-muted/50 transition-colors",
                    !notif.read && "bg-accent/5",
                  )}
                >
                  <div className="flex gap-3 items-start">
                    <span
                      className={cn(
                        "w-2 h-2 rounded-full mt-1.5 shrink-0",
                        notifColors[notif.type],
                      )}
                    />
                    <div className="min-w-0">
                      <p
                        className={cn(
                          "text-xs font-semibold truncate",
                          !notif.read && "text-foreground",
                        )}
                      >
                        {notif.title}
                      </p>
                      <p className="text-xs text-muted-foreground line-clamp-2">
                        {notif.message}
                      </p>
                      <p className="text-[10px] text-muted-foreground mt-1">
                        {formatDistanceToNow(new Date(notif.timestamp), {
                          addSuffix: true,
                        })}
                      </p>
                    </div>
                  </div>
                </button>
              ))}
            </ScrollArea>
          </PopoverContent>
        </Popover>

        {/* User menu */}
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button
              variant="ghost"
              size="icon"
              data-ocid="navbar.user_menu"
              className="w-8 h-8"
              aria-label="User menu"
            >
              <Avatar className="w-7 h-7">
                <AvatarFallback className="bg-accent text-accent-foreground text-[10px] font-bold">
                  SP
                </AvatarFallback>
              </Avatar>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end" className="w-48">
            <DropdownMenuLabel>
              <p className="text-xs font-semibold">Suresh Prasad</p>
              <p className="text-xs text-muted-foreground font-normal">
                suresh@aipsa.edu.in
              </p>
            </DropdownMenuLabel>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              data-ocid="navbar.profile_link"
              className="text-xs cursor-pointer"
            >
              <User className="w-3 h-3 mr-2" /> Profile
            </DropdownMenuItem>
            <DropdownMenuItem
              data-ocid="navbar.settings_link"
              className="text-xs cursor-pointer"
            >
              <Settings className="w-3 h-3 mr-2" /> Settings
            </DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem
              data-ocid="navbar.logout_button"
              className="text-xs text-destructive cursor-pointer focus:text-destructive"
            >
              <LogOut className="w-3 h-3 mr-2" /> Sign Out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </div>
    </header>
  );
}

// src/frontend/src/lib/components/layout/Navbar.svelte
<script lang="ts">
	import { appStore } from '$lib/stores/app.svelte';
	import { cn } from '$lib/utils';
	import {
		Bell,
		ChevronDown,
		LogOut,
		Menu,
		Moon,
		Search,
		Settings,
		Sun,
		User
	} from 'lucide-svelte';

	let { title = '' } = $props();

	const roles = [
		{ value: 'super_admin', label: 'Super Admin' },
		{ value: 'school_admin', label: 'School Admin' },
		{ value: 'teacher', label: 'Teacher' },
		{ value: 'parent', label: 'Parent' },
		{ value: 'student', label: 'Student' }
	];

	// For now, hardcode some state
	const currentRole = 'super_admin';
	const currentRoleLabel = roles.find((r) => r.value === currentRole)?.label ?? 'Super Admin';
	const unreadCount = 3;
</script>

<header
	class="flex h-14 shrink-0 items-center gap-3 border-b border-border bg-card px-4 shadow-xs"
>
	<!-- Left -->
	<div class="flex items-center gap-2 min-w-0">
		<button
			type="button"
			onclick={() => appStore.toggleSidebar()}
			class="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-muted"
			aria-label="Toggle sidebar"
		>
			<Menu class="h-4 w-4" />
		</button>
		{#if title}
			<h1 class="hidden truncate text-sm font-semibold text-foreground md:block">
				{title}
			</h1>
		{/if}
	</div>

	<!-- Search -->
	<div class="mx-auto max-w-sm flex-1">
		<div class="relative">
			<Search class="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
			<input
				placeholder="Search schools, students, leads…"
				class="h-8 w-full rounded-md border border-input/50 bg-muted/50 pl-9 text-sm focus:bg-background"
			/>
			<kbd
				class="absolute right-2 top-1/2 hidden -translate-y-1/2 items-center gap-0.5 rounded bg-muted px-1 text-[10px] text-muted-foreground sm:flex"
			>
				⌘K
			</kbd>
		</div>
	</div>

	<!-- Right actions -->
	<div class="flex shrink-0 items-center gap-1">
		<!-- Role switcher -->
		<button
			type="button"
			class="hidden h-8 items-center gap-1 rounded-md border border-input/50 px-3 text-xs md:flex hover:bg-muted"
		>
			{currentRoleLabel}
			<ChevronDown class="h-3 w-3" />
		</button>

		<!-- Dark mode -->
		<button
			type="button"
			onclick={() => appStore.toggleDarkMode()}
			class="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-muted"
			aria-label="Toggle dark mode"
		>
			{#if appStore.isDarkMode}
				<Sun class="h-4 w-4" />
			{:else}
				<Moon class="h-4 w-4" />
			{/if}
		</button>

		<!-- Notifications -->
		<button
			type="button"
			class="relative flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-muted"
			aria-label="Notifications"
		>
			<Bell class="h-4 w-4" />
			{#if unreadCount > 0}
				<span
					class="absolute -right-0.5 -top-0.5 flex h-4 w-4 items-center justify-center rounded-full bg-destructive text-[10px] font-bold text-destructive-foreground"
				>
					{unreadCount}
				</span>
			{/if}
		</button>

		<!-- User menu -->
		<button
			type="button"
			class="flex h-8 w-8 items-center justify-center rounded-md text-muted-foreground hover:bg-muted"
			aria-label="User menu"
		>
			<div class="flex h-7 w-7 items-center justify-center rounded-full bg-accent text-[10px] font-bold text-accent-foreground">
				SP
			</div>
		</button>
	</div>
</header>
